manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kumamaki-git  # ← これがroBa本体の定義に必須です！
      url-base: https://github.com/kumamaki-git
    - name: badjeff      # トラックボール(PMW3610)のドライバー
      url-base: https://github.com/badjeff
    - name: zettaface    # ジェスチャーの基盤モジュール
      url-base: https://github.com/zettaface
    - name: kot149       # ジェスチャー機能本体
      url-base: https://github.com/kot149
    - name: ssbb         # 入力監視用モジュール
      url-base: https://github.com/ssbb

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    - name: zmk-input-processor-keybind
      remote: zettaface
      revision: main
    - name: zmk-mouse-gesture
      remote: kot149
      revision: v1
    - name: zmk-listeners
      remote: ssbb
      revision: v1

  self:
    path: config
